# Generated by Django 4.2 on 2024-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
